paths:
  cache_dir: "/mnt/sda1/home/sparc/nqthinh/DeepTokenEEG_Alzheimer_CLS/outputs/cache_unified/multidataset/alpha"
  #cache_dir: "/mnt/sda1/home/sparc/nqthinh/DeepTokenEEG_Alzheimer_CLS/outputs/cache_unified/single/ADFTD/alpha"

signal:
  band_name: "alpha"

labels:
  HC: 0
  AD: 1

split:
  ratios: [0.6, 0.2, 0.2]
  seed: 45
