model:
  d_model: 32
  dropout: 0.5
  num_class: 2
  tokenizer:
    method: "conv"
    kernel_size: 7
  resnet:
    n_blocks: 5        # <- ablation thay đổi 1..4
    dilations: [2, 2, 2, 2, 2]  # dùng n_blocks cái đầu
